application: hanggammon
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /xml
  static_dir: static/xml

- url: /.*
  script: _go_app
